plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.99'
}

version = '8.0.0'
base.archivesName = "blockomorph-1.21.8-neoforge"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.8.27"

    runs {
        client {
            client()
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

jar {
    destinationDirectory = file("D:\\SERVER\\mods\\mod\\blockomorph\\jar\\outPut")
}
