modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="blockomorph"
version="1.0.8"
displayName="Block'oMorph"
logoFile="logo.png"
authors="151gamemode1chit"
description="This mod allows players morph into blocks with all the main features of the block."

[[dependencies.blockomorph]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



